In [4]:
import numpy as np

# numpy arry 

In [5]:
arrytest = np.array([1,2,2,3,4])

In [6]:
arrytest

array([1, 2, 2, 3, 4])

In [7]:
print(f'arrytest[1] is : {arrytest[1]}')
print(f'arrytest[0] is : {arrytest[0]}')
print(f'arrytest[5] is : {arrytest[4]}')

arrytest[1] is : 2
arrytest[0] is : 1
arrytest[5] is : 4


In [8]:
arrytest.dtype

dtype('int64')

In [9]:
arrytest.shape

(5,)

In [10]:
matrix = np.array([(1,2),(8,3),(9,4)])
matrix

array([[1, 2],
       [8, 3],
       [9, 4]])

In [11]:
matrix[2,1]

4

In [12]:
matrix [0,:]

array([1, 2])

In [13]:
print(f'shape of matrix is  : {matrix.shape}')
print(f'Number of matrix dimensions  : {matrix.ndim}')

shape of matrix is  : (3, 2)
Number of matrix dimensions  : 2


In [14]:
np.reshape(matrix,(2,3))

array([[1, 2, 8],
       [3, 9, 4]])

In [15]:
np.reshape(matrix,(1,-1))

array([[1, 2, 8, 3, 9, 4]])

In [16]:
np.reshape(matrix,(-1,1))

array([[1],
       [2],
       [8],
       [3],
       [9],
       [4]])

In [17]:
matrix <3

array([[ True,  True],
       [False, False],
       [False, False]])

In [19]:
matrix.min(axis = 0)

array([1, 2])

In [20]:
matrix.max(axis = 1)

array([2, 8, 9])

In [22]:
np.sort(matrix,axis = None)

array([1, 2, 3, 4, 8, 9])

In [23]:
np.sort(matrix)

array([[1, 2],
       [3, 8],
       [4, 9]])

In [24]:
np.linspace(1,10,num=5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [51]:
np.linspace(0,10,21)

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [49]:
np.zeros(2)

array([0., 0.])

In [27]:
np.ones(3)

array([1., 1., 1.])

In [53]:
np.empty(3)

array([1.        , 2.71828183, 7.3890561 ])

In [29]:
np.full((2,3),4)

array([[4, 4, 4],
       [4, 4, 4]])

In [32]:
arry = np.arange(3)
arry

array([0, 1, 2])

In [34]:
np.sqrt(arry)

array([0.        , 1.        , 1.41421356])

In [43]:
matrix.sum(axis = 0)

array([18,  9])

In [44]:
matrix.sum(axis = 1)

array([ 3, 11, 13])

In [56]:
np.random.randint(0,50)

16

In [59]:
np.random.seed(1)
np.random.randint(0,50)

37

In [60]:
np.random.rand(5)

array([0.99718481, 0.93255736, 0.12812445, 0.99904052, 0.23608898])

In [66]:
np.random.uniform(5,size = 25)

array([2.50388005, 2.35745708, 3.80601882, 3.21546198, 4.11150181,
       4.70654331, 3.12304589, 4.61531096, 1.38651933, 4.52203813,
       2.90080249, 4.66550798, 1.33255466, 1.35820647, 3.80427955,
       2.66244352, 2.73635189, 2.54424673, 1.17385737, 3.95608408,
       4.07593831, 2.86620604, 1.20024745, 3.02776163, 2.83759796])